# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d95be7db0855c31e52def4eaa6a6c4366bab1e9ac64c7ac9f77979ae6625ae0d30ee989f52dc75c725183bbb0bbfe2dcbaf642b79253c5df7a96cb776999de32

test:
  secret_key_base: 6518a86e84d0aea190e2b5edd2a61e53427e960778910ad7d959845e2096c168e768a0756704e937f1b7aa72abaeb5ac256996411fb0d078b27ff8248b977195

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
